config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasklists#index'
  resources :tasklists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  def index
      @tasklists = Task.all
  end

  def show
      @tasklist = Task.find(params[:id])
  end

  def new
      @tasklist = Task.new
  end

  def create
    @tasklist = Task.new(tasklist_params)

    if @tasklist.save
      flash[:success] = 'Task が正常に投稿されました'
      redirect_to @message
    else
      flash.now[:danger] = 'Task が投稿されませんでした'
      render :new
    end      
  end

  def edit
      @tasklist = Task.find(params[:id])
  end

  def update
    @tasklist = Task.find(params[:id])

    if @tasklist.update(tasklist_params)
      flash[:success] = 'Task は正常に更新されました'
      redirect_to @tasklist
    else
      flash.now[:danger] = 'Task は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @tasklist = Task.find(params[:id])
    @tasklist.destroy

    flash[:success] = 'Task は正常に削除されました'
    redirect_to tasklists_url

  end    
    
    
  private

  # Strong Parameter
  def tasklist_params
    params.require(:tasklist).permit(:content)
  end    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_tasklists.html.erb
<% flash.each do |tasklist_type, tasklist| %>
  <div><%= tasklist %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/flash_tasklists' %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/tasklists/edit.html.erb
<h1>id: <%= @tasklist.id %> のタスク編集ページ</h1>

<%= form_for @tasklist,:url => {:action => :edit} do |f| %>
  <%= f.label :content, 'メッセージ' %>
  <%= f.text_field :content %>

  <%= f.submit '投稿' %>
<% end %>

<%= link_to '一覧に戻る', tasklists_path %>

app/views/tasklists/index.html.erb
<h1>タスク一覧</h1>

<ul>
  <% @tasklists.each do |tasklist| %>
    <li><%= link_to tasklist.id, tasklist_path(tasklist) %> : <%= tasklist.content %></li>
  <% end %>
</ul>

<%= link_to '新規タスクの投稿', new_tasklist_path %>

app/views/tasklists/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= form_for @tasklist,:url => {:action => :new} do |f| %>
  <%= f.label :content, 'メッセージ' %>
  <%= f.text_field :content %>

  <%= f.submit '投稿' %>
<% end %>

<%= link_to '一覧に戻る', tasklists_path %>

app/views/tasklists/show.html.erb
<h1>id: <%= @tasklist.id %> のタスク詳細ページ</h1>

<p><%= @tasklist.content %></p>

<%= link_to '一覧に戻る', tasklists_path %>
<%= link_to 'このタスクを編集する', edit_tasklist_path(@tasklist) %>
<%= link_to 'このタスクを削除する', tasklists_path, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>